name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java and sbt
        uses: guardian/setup-scala@v1

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: AP Feed - Build GuCDK
        working-directory: 'associated-press/cdk'
        run: |
          npm ci
          npm run test
          npm run synth
      - name: AP feed - Scala build
        run: |
          sbt clean scalafmtCheckAll compile test Debian/packageBin normalisePackageName

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumber: ${{ env.GITHUB_RUN_NUMBER }}
          projectName: editorial-tools:grid-feeds
          configPath: associated-press/cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            associated-press-feed:
              - associated-press/target/associated-press-feed.deb
            associated-press-feed-v2:
              - associated-press/target/associated-press-feed.deb
            cdk.out:
              - associated-press/cdk/cdk.out/AssociatedPressFeed-CODE.template.json
              - associated-press/cdk/cdk.out/AssociatedPressFeed-PROD.template.json
