name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - name: test
        run: |
          sbt -v test
      - name: check formatting
        run: |
          sbt scalafmtCheckAll
      - uses: guardian/actions-riff-raff@v2
        with:
          projectName: editorial-tools::grid-feeds
          configPath: cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out
            grid-feeds:
              - target/grid-feeds.deb
         app: grid-feeds
         config: |
          stacks:
            - [media-service]
          regions:
            - eu-west-1
          allowedStages:
            - CODE
            - PROD
          deployments:
            associated-press-feed:
              type: autoscaling
              parameters:
                bucket: aws-some-bucket
                cacheControl: private
                publicReadAcl: false
            
              