name: Snyk
on:
  push:
    branches:
      - main
      - integrate-snyk-javascript-scala-shell-typescript
  workflow_dispatch: 
jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
